const API_STATUS_CODES = {
    SUCCESS: 200,
    NOT_FOUND: 404,
    AUTHORIZATION_FAILED: 401,
    ERROR_CODE: 400,
    INTERNAL_SERVER_ERROR: 500,
    DUPLICATE_ENTRY: 11000,
};
const RESPONSE_MESSAGES = {
    SUCCESS: 'Success',
    AUTHORIZATION_FAILED: 'Authorization failed',
    DUPLICATE_ENTRY: 'email already exist.',
};

module.exports = { API_STATUS_CODES, RESPONSE_MESSAGES }
